version: "3"

services:

    nginx:
        build: nginx/
        ports:
            - "443:443"
        volumes:
            - wordpress-files:/root/data

    wordpress:
        build: wordpress/
        volumes:
            - wordpress-files:/root/data

volumes:
    wordpress-files:
        driver_opts:
            type: none
            o: bind
            device: /home/user42/data
