version: "3"

services:

    nginx:
        build: nginx/
        ports:
            - "443:443"
        volumes:
            - wordpress-files:/var/www/wordpress

    wordpress:
        environment:
            - DB_USERNAME
            - DB_PASSWORD
        build: wordpress/
        volumes:
            - wordpress-files:/root/data

    mariadb:
        environment:
            - DB_USERNAME
            - DB_PASSWORD
        build: mariadb/
        volumes:
            - database:/root/database

volumes:

    wordpress-files:

    database:
