version: "3"

services:

    nginx:
        build: nginx/
        ports:
            - "443:443"
        volumes:
            - /home/${USER}/data/wordpress-files:/var/www/rkowalsk.42.fr/
        restart: always
        networks:
            - reso

    wordpress:
        environment:
            - DB_USERNAME
            - DB_NAME
            - DB_PASSWORD
        build: wordpress/
        volumes:
            - /home/${USER}/data/wordpress-files:/var/www/rkowalsk.42.fr/
        restart: always
        networks:
            - reso

    mariadb:
        environment:
            - DB_USERNAME
            - DB_NAME
            - DB_PASSWORD
        build: mariadb/
        volumes:
            - /home/${USER}/data/database:/var/lib/mysql/
        restart: always
        networks:
            - reso

networks:
        reso:
