version: "3"

services:

    nginx:
        build: nginx/
        ports:
            - "443:443"
        volumes:
            - wordpress-files:/var/www/rkowalsk.42.fr/
        restart: always

    wordpress:
        environment:
            - DB_USERNAME
            - DB_NAME
            - DB_PASSWORD
        build: wordpress/
        volumes:
            - wordpress-files:/var/www/rkowalsk.42.fr/
        restart: always

    mariadb:
        environment:
            - DB_USERNAME
            - DB_NAME
            - DB_PASSWORD
        build: mariadb/
        volumes:
            - database:/var/lib/mysql
        restart: always

volumes:

    wordpress-files:

    database:
